import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FilePlus2, LockKeyhole, Plus, UserRoundCheck } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

export default function AcademyAdmin() {
  const { user, loading } = useAuth();
  const overview = trpc.academy.adminOverview.useQuery(undefined, { enabled: user?.role === "admin" });
  const refresh = () => overview.refetch();
  const activate = trpc.academy.adminActivateMembership.useMutation({ onSuccess: refresh });
  const createCourse = trpc.academy.adminCreateCourse.useMutation({ onSuccess: refresh });
  const createModule = trpc.academy.adminCreateModule.useMutation({ onSuccess: refresh });
  const createLesson = trpc.academy.adminCreateLesson.useMutation({ onSuccess: refresh });
  const updateModule = trpc.academy.adminUpdateModule.useMutation({ onSuccess: refresh });
  const updateLesson = trpc.academy.adminUpdateLesson.useMutation({ onSuccess: refresh });
  const createMaterial = trpc.academy.adminCreateMaterial.useMutation({ onSuccess: refresh });
  const [studentId, setStudentId] = useState("");
  const [course, setCourse] = useState({ title: "", slug: "", description: "" });
  const [module, setModule] = useState({ courseId: "", title: "", description: "", sortOrder: "1" });
  const [lesson, setLesson] = useState({ courseId: "", moduleId: "", title: "", description: "", sortOrder: "1" });
  const [material, setMaterial] = useState({ lessonId: "", title: "", url: "" });

  if (loading) return <AdminShell><div className="academy-loading">Abrindo gestão Academy...</div></AdminShell>;
  if (!user) return <AdminShell><AdminGate title="Entre para continuar." description="O painel administrativo é exclusivo para a equipe da Academy." action="Entrar" onAction={() => startLogin()} /></AdminShell>;
  if (user.role !== "admin") return <AdminShell><AdminGate title="Este painel é privado." description="Você não possui permissão de gestão da Academy." action="Voltar para Academy" href="/academy" /></AdminShell>;

  const students = overview.data?.students ?? [];
  const courses = overview.data?.courses ?? [];
  const lessons = courses.flatMap(item => item.modules.flatMap(itemModule => itemModule.lessons));
  const modules = courses.flatMap(item => item.modules);
  return <AdminShell>
    <section className="academy-welcome"><div><p className="academy-kicker">Gestão Academy</p><h1>Conteúdo com método.</h1><p>Ative acessos e mantenha o catálogo da Academy atualizado.</p></div><Link href="/academy" className="academy-back-link">Voltar para a Academy</Link></section>
    <div className="academy-admin-grid">
      <AdminCard icon={<UserRoundCheck size={18} />} kicker="Assinaturas" title="Ativar aluno"><p>Use o ID interno para liberar cursos publicados.</p><form className="academy-admin-form" onSubmit={event => { event.preventDefault(); activate.mutate({ userId: Number(studentId) }); }}><label>ID do aluno<input value={studentId} onChange={event => setStudentId(event.target.value)} inputMode="numeric" placeholder="Ex.: 12" /></label><button className="academy-primary-button" disabled={activate.isPending || !studentId}>Ativar acesso <CheckCircle2 size={16} /></button></form></AdminCard>
      <AdminCard icon={<Plus size={18} />} kicker="Catálogo" title="Novo curso"><form className="academy-admin-form" onSubmit={event => { event.preventDefault(); createCourse.mutate({ title: course.title, slug: course.slug, description: course.description }); }}><label>Título<input value={course.title} onChange={event => setCourse({ ...course, title: event.target.value })} placeholder="Ex.: Fundamentos da terapia capilar" /></label><label>Slug<input value={course.slug} onChange={event => setCourse({ ...course, slug: event.target.value })} placeholder="fundamentos-terapia-capilar" /></label><label>Descrição<textarea value={course.description} onChange={event => setCourse({ ...course, description: event.target.value })} placeholder="Descreva a promessa da trilha." /></label><button className="academy-primary-button" disabled={createCourse.isPending || !course.title || !course.slug || course.description.length < 10}>Criar curso <Plus size={16} /></button></form></AdminCard>
      <AdminCard icon={<Plus size={18} />} kicker="Estrutura" title="Novo módulo"><form className="academy-admin-form" onSubmit={event => { event.preventDefault(); createModule.mutate({ courseId: Number(module.courseId), title: module.title, description: module.description, sortOrder: Number(module.sortOrder) }); }}><label>Curso<select value={module.courseId} onChange={event => setModule({ ...module, courseId: event.target.value })}><option value="">Selecione</option>{courses.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Título<input value={module.title} onChange={event => setModule({ ...module, title: event.target.value })} /></label><label>Descrição<textarea value={module.description} onChange={event => setModule({ ...module, description: event.target.value })} /></label><button className="academy-primary-button" disabled={createModule.isPending || !module.courseId || !module.title}>Criar módulo <Plus size={16} /></button></form></AdminCard>
      <AdminCard icon={<Plus size={18} />} kicker="Aulas" title="Nova aula"><form className="academy-admin-form" onSubmit={event => { event.preventDefault(); createLesson.mutate({ courseId: Number(lesson.courseId), moduleId: Number(lesson.moduleId), title: lesson.title, description: lesson.description, sortOrder: Number(lesson.sortOrder) }); }}><label>Curso<select value={lesson.courseId} onChange={event => setLesson({ ...lesson, courseId: event.target.value })}><option value="">Selecione</option>{courses.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Módulo<select value={lesson.moduleId} onChange={event => setLesson({ ...lesson, moduleId: event.target.value })}><option value="">Selecione</option>{modules.filter(item => !lesson.courseId || item.courseId === Number(lesson.courseId)).map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Título<input value={lesson.title} onChange={event => setLesson({ ...lesson, title: event.target.value })} /></label><label>Descrição<textarea value={lesson.description} onChange={event => setLesson({ ...lesson, description: event.target.value })} /></label><button className="academy-primary-button" disabled={createLesson.isPending || !lesson.courseId || !lesson.moduleId || !lesson.title}>Criar aula <Plus size={16} /></button></form></AdminCard>
      <AdminCard icon={<FilePlus2 size={18} />} kicker="Materiais" title="Publicar link"><form className="academy-admin-form" onSubmit={event => { event.preventDefault(); createMaterial.mutate({ lessonId: Number(material.lessonId), title: material.title, materialType: "link", url: material.url }); }}><label>Aula<select value={material.lessonId} onChange={event => setMaterial({ ...material, lessonId: event.target.value })}><option value="">Selecione</option>{lessons.map(item => <option key={item.id} value={item.id}>#{item.id} · {item.title}</option>)}</select></label><label>Nome<input value={material.title} onChange={event => setMaterial({ ...material, title: event.target.value })} /></label><label>URL pública<input type="url" value={material.url} onChange={event => setMaterial({ ...material, url: event.target.value })} placeholder="https://..." /></label><button className="academy-primary-button" disabled={createMaterial.isPending || !material.lessonId || !material.title || !material.url}>Publicar material <FilePlus2 size={16} /></button></form></AdminCard>
    </div>
    <section className="academy-admin-table"><div className="academy-section-heading"><div><p className="academy-kicker">Alunos cadastrados</p><h2>Acessos recentes.</h2></div><span>{students.length} alunos</span></div>{students.map(student => <div className="academy-admin-row" key={student.id}><div><strong>#{student.id} · {student.name ?? "Sem nome"}</strong><span>{student.email ?? "Sem e-mail"}</span></div><span className={student.membershipStatus === "active" ? "is-active" : "is-pending"}>{student.membershipStatus === "active" ? "Ativo" : "Sem assinatura"}</span></div>)}</section>
    <section className="academy-admin-table academy-admin-edit-table"><div className="academy-section-heading"><div><p className="academy-kicker">Edição do catálogo</p><h2>Atualize a trilha.</h2></div><span>{modules.length} módulos · {lessons.length} aulas</span></div>{modules.map(item => <form className="academy-admin-inline-form" key={item.id} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); updateModule.mutate({ id: item.id, title: String(data.get("title")), description: String(data.get("description")), sortOrder: Number(data.get("sortOrder")) }); }}><div><span className="academy-admin-inline-label">Módulo #{item.id}</span><input name="title" defaultValue={item.title} aria-label="Título do módulo" /><input name="description" defaultValue={item.description ?? ""} aria-label="Descrição do módulo" /></div><input className="academy-admin-order" name="sortOrder" type="number" min="1" defaultValue={item.sortOrder} aria-label="Ordem do módulo" /><button className="academy-secondary-button" disabled={updateModule.isPending}>Salvar módulo</button></form>)}{lessons.map(item => <form className="academy-admin-inline-form" key={item.id} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); updateLesson.mutate({ id: item.id, title: String(data.get("title")), description: String(data.get("description")), sortOrder: Number(data.get("sortOrder")) }); }}><div><span className="academy-admin-inline-label">Aula #{item.id}</span><input name="title" defaultValue={item.title} aria-label="Título da aula" /><input name="description" defaultValue={item.description ?? ""} aria-label="Descrição da aula" /></div><input className="academy-admin-order" name="sortOrder" type="number" min="1" defaultValue={item.sortOrder} aria-label="Ordem da aula" /><button className="academy-secondary-button" disabled={updateLesson.isPending}>Salvar aula</button></form>)}</section>
  </AdminShell>;
}

function AdminCard({ icon, kicker, title, children }: { icon: React.ReactNode; kicker: string; title: string; children: React.ReactNode }) { return <section className="academy-admin-card"><div className="academy-admin-card-heading">{icon}<div><p className="academy-kicker">{kicker}</p><h2>{title}</h2></div></div>{children}</section>; }
function AdminGate({ title, description, action, onAction, href }: { title: string; description: string; action: string; onAction?: () => void; href?: string }) { return <section className="academy-gate"><div className="academy-gate-mark"><LockKeyhole size={18} /></div><p className="academy-kicker">Gestão restrita</p><h1>{title}</h1><p>{description}</p>{href ? <Link href={href} className="academy-primary-button">{action}</Link> : <button className="academy-primary-button" type="button" onClick={onAction}>{action}</button>}</section>; }
function AdminShell({ children }: { children: React.ReactNode }) { return <div className="academy-shell"><header className="academy-header"><Link href="/" className="academy-brand"><span className="academy-brand-mark">SL</span><span><strong>Samia Lima</strong><em>Academy · Gestão</em></span></Link><Link href="/academy" className="academy-header-link">Minha área</Link></header><main className="academy-main">{children}</main><footer className="academy-footer"><span>Academy Samia Lima</span><span>Gestão protegida</span></footer></div>; }
